env:
  browser: true
extends: 'eslint:recommended'
rules:
  accessor-pairs: error
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: 'off'
  block-spacing:
    - error
    - never
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  callback-return: error
  camelcase: error
  class-methods-use-this: error
  comma-dangle: error
  comma-spacing: 'off'
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing:
    - error
    - never
  consistent-return: 'off'
  consistent-this: 'off'
  curly: 'off'
  default-case: error
  dot-location: error
  dot-notation: error
  eol-last: 'off'
  eqeqeq: 'off'
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - never
  func-style: 'off'
  generator-star-spacing: error
  global-require: error
  guard-for-in: 'off'
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent: 'off'
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: 'off'
  keyword-spacing: 'off'
  line-comment-position: error
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  lines-around-directive: error
  max-depth: error
  max-len: 'off'
  max-lines: error
  max-nested-callbacks: error
  max-params: error
  max-statements: 'off'
  max-statements-per-line: 'off'
  multiline-ternary:
    - error
    - never
  new-cap: error
  new-parens: 'off'
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 'off'
  no-alert: error
  no-array-constructor: error
  no-bitwise: 'off'
  no-caller: error
  no-catch-shadow: error
  no-cond-assign:
    - error
    - except-parens
  no-confusing-arrow: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: 'off'
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-globals: 'off'
  no-implied-eval: error
  no-inline-comments: error
  no-inner-declarations:
    - error
    - functions
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: 'off'
  no-mixed-requires: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-negated-condition: 'off'
  no-nested-ternary: 'off'
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: 'off'
  no-path-concat: error
  no-plusplus: 'off'
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: 'off'
  no-script-url: error
  no-self-compare: error
  no-sequences: 'off'
  no-shadow: 'off'
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unsafe-negation: error
  no-unused-expressions: 'off'
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-var: 'off'
  no-void: 'off'
  no-warning-comments: error
  no-whitespace-before-property: error
  no-with: error
  object-curly-newline: error
  object-curly-spacing: 'off'
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  object-shorthand: error
  one-var: 'off'
  one-var-declaration-per-line: 'off'
  operator-assignment:
    - error
    - always
  operator-linebreak: error
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-numeric-literals: error
  prefer-reflect: 'off'
  prefer-rest-params: 'off'
  prefer-spread: 'off'
  prefer-template: 'off'
  quote-props: 'off'
  quotes: 'off'
  radix: error
  require-jsdoc: 'off'
  rest-spread-spacing: error
  semi: 'off'
  semi-spacing:
    - error
    - after: false
      before: false
  sort-imports: error
  sort-keys: 'off'
  sort-vars: 'off'
  space-before-blocks: 'off'
  space-before-function-paren: 'off'
  space-in-parens:
    - error
    - never
  space-infix-ops: 'off'
  space-unary-ops:
    - error
    - nonwords: false
      words: false
  spaced-comment: error
  strict:
    - error
    - never
  symbol-description: error
  template-curly-spacing: error
  unicode-bom:
    - error
    - never
  valid-jsdoc: error
  vars-on-top: 'off'
  wrap-iife: 'off'
  wrap-regex: error
  yield-star-spacing: error
  yoda: 'off'
