# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Tech at GSA
email: cto@gsa.gov
description: >
  We utilize collaborative practices and modern IT tools to facilitate a new GSA.

baseurl: ""
url: "http://tech.gsa.gov"
markdown: kramdown
include:
  - '_pages'
exclude:
  - 'README.md'
  - 'LICENSE.md'
  - 'Rakefile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'package.json'
  - 'node_modules'
  - 'gulpfile.js'
  - '_test'

collections:
  team:
    permalink: /team/:name/
    output: true
  guides:
    permalink: /guides/:title/
    output: true

defaults:
  -
    values:
      layout: page
  -
    scope:
      type: guides
    values:
      layout: guide

forms:
  - type: newsletter
    heading: Ask a question
    url: https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSesCR4CG0zSRhYLTY7Oq04PaD99Uk1rJrFjmohsW8vYwtNxiw/formResponse
    button: Send
    privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice.</a>
    fields:
      - type: subject
        name: entry.1866334422
        label: Subject
      - type: text
        name: entry.143577008
        label: How can we help?
      - type: email
        name: entry.211727308
        label: Your email address

itstandards:
    - type: itstandards
      heading: Ask a question
      url: 
      button: Submit
      privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice.</a>
      fields:
        - type: Name
          name: 
          label: Requestor Name
        - type: email
          name: 
          label: Requestor Email Adress
        - type: capability
          name: 
          label: What capability, function, or task do you need to perform?
        - type: gear
          name: 
          label: Please confirm that you have reviewed GEAR and there are no suitable options for your business needs.
        - type: software
          name: 
          label: What is the name of the software you want approved? Include vendor and version number, if known.
        - type: type
          name: 
          label: What type of software is this?
        - type: justification
          name: 
          label: Please provide a business justification for this request (including information on any alternatives that were explored.)
        - type: reviewed
          name: 
          label: Did you speak with anyone within the GSA IT organization prior to submitting the request?
        - type: reviewed-office
          name: 
          label: If yes, which office did you speak with?
        - type: users
          name: 
          label: How many people do you anticipate having the same need?
        - type: data
          name: 
          label: Will you be storing any sensitive data within this tool?
        - type: management
          name: 
          label: Does your management support this request?
        - type: costs
          name: 
          label: Please provide estimated costs, if available.

intake:
  - type: intake
    heading:
    url: https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLScC37I1E3pCD8qXfnhUvorJKrMNRL9edezZvEYUIdPt5GE0dg/formResponse
    button: Submit
    privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice.</a>
    fields:
      - type: submitter name
        name: entry.20395120
        label: Your Name
      - type: submitter email
        name: entry.525550689
        label: Your Email
      - type: problem statement
        name: entry.1314705153
        label: Problem Statement
      - type: purpose
        name: entry.1645822807
        label: Purpose
      - type: scope
        name: entry.76271973
        label: Scope
      - type: strategic goals
        name: entry.285185669
        label: Strategic Goals
      - type: Business Lines
        name: entry.1811656482
        label: Business Lines
      - type: name
        name: entry.460893215
        label: Stakeholder Name
      - type: email
        name: entry.639786444
        label: Stakeholder Email
      - type: phone
        name: entry.1169908858
        label: Stakeholder Phone
      - type: funds
        name: entry.1133652762
        label: Requested Funds
      - type: source
        name: entry.90307167
        label: Funding Source
