# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: GSA Chief Technology Officer
email: cto@gsa.gov
description: >
  The Office of the CTO provides guidance in transforming GSA IT toward modern IT practices.
baseurl: ""
url: "http://cto.gsa.gov"
markdown: kramdown

collections:
  team:
    permalink: /team/:name/
    output: true
  hub:
    permalink: /hub/:title/
    output: true
